In [1]:
import numpy as np

In [5]:
perd_path = 'results/ETTm2_96_96_Autoformer_ETTm2_ftS_sl96_ll96_pl96_dm512_nh8_el2_dl1_df2048_fc3_ebtimeF_dtTrue_Exp_0/pred.npy'
ground_truth_path = "results/ETTm2_96_96_Autoformer_ETTm2_ftS_sl96_ll96_pl96_dm512_nh8_el2_dl1_df2048_fc3_ebtimeF_dtTrue_Exp_0/true.npy"
metric_path = "results/ETTm2_96_96_Autoformer_ETTm2_ftS_sl96_ll96_pl96_dm512_nh8_el2_dl1_df2048_fc3_ebtimeF_dtTrue_Exp_0/metrics.npy"
# Load the array from the .npy file
pred_result = np.load(perd_path)
ground_truth = np.load(ground_truth_path)
metric = np.load(metric_path)


In [3]:
pred_result

array([[[-1.979198 ],
        [-1.9711035],
        [-1.978174 ],
        ...,
        [-2.1095586],
        [-2.1093984],
        [-1.7872975]],

       [[-1.8704621],
        [-1.8869975],
        [-1.8825841],
        ...,
        [-2.0438516],
        [-2.0383453],
        [-1.8135083]],

       [[-1.8838171],
        [-1.8811904],
        [-1.9614427],
        ...,
        [-2.0433664],
        [-1.9921536],
        [-1.9024211]],

       ...,

       [[-1.6899797],
        [-1.7413955],
        [-1.8031439],
        ...,
        [-1.6760043],
        [-1.6871431],
        [-1.6953216]],

       [[-1.7876582],
        [-1.8786833],
        [-1.8891665],
        ...,
        [-1.6270245],
        [-1.6281726],
        [-1.6425594]],

       [[-1.8110197],
        [-1.909989 ],
        [-1.944381 ],
        ...,
        [-1.5407176],
        [-1.616095 ],
        [-1.5922885]]], dtype=float32)

In [4]:
ground_truth

array([[[-1.825391 ],
        [-1.7666796],
        [-1.7666796],
        ...,
        [-1.6493905],
        [-1.6493905],
        [-1.7081019]],

       [[-1.7666796],
        [-1.7666796],
        [-1.7666796],
        ...,
        [-1.6493905],
        [-1.7081019],
        [-1.7081019]],

       [[-1.7666796],
        [-1.7666796],
        [-1.7666796],
        ...,
        [-1.7081019],
        [-1.7081019],
        [-1.7373908]],

       ...,

       [[-2.147903 ],
        [-2.147903 ],
        [-2.147903 ],
        ...,
        [-1.7373908],
        [-1.7373908],
        [-1.7373908]],

       [[-2.147903 ],
        [-2.147903 ],
        [-2.2065477],
        ...,
        [-1.7373908],
        [-1.7373908],
        [-1.7373908]],

       [[-2.147903 ],
        [-2.2065477],
        [-2.2065477],
        ...,
        [-1.7373908],
        [-1.7373908],
        [-1.7373908]]], dtype=float32)

In [6]:
metric

array([0.31176558, 0.16243935, 0.40303764, 0.23098294, 0.15680183],
      dtype=float32)