In [1]:
import pandas as pd

/var/folders/3c/4336tt352pn6hnc003pk93080000gn/T/ipykernel_6593/4080736814.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [17]:
df_raw = pd.read_csv("dataset/ETT-small/ETTm2.csv")

In [18]:
df_raw

date       HUFL    HULL       MUFL    MULL    LUFL  \
0      2016-07-01 00:00:00  41.130001  12.481  36.535999   9.355   4.424   
1      2016-07-01 00:15:00  39.622002  11.309  35.543999   8.551   3.209   
2      2016-07-01 00:30:00  38.868000  10.555  34.365002   7.586   4.435   
3      2016-07-01 00:45:00  35.518002   9.214  32.569000   8.712   4.435   
4      2016-07-01 01:00:00  37.528000  10.136  33.936001   7.532   4.435   
...                    ...        ...     ...        ...     ...     ...   
69675  2018-06-26 18:45:00  42.722000  12.230  54.014000  12.652 -11.525   
69676  2018-06-26 19:00:00  38.868000  10.052  49.859001  10.669 -11.525   
69677  2018-06-26 19:15:00  39.622002  11.057  50.448002  11.795 -10.299   
69678  2018-06-26 19:30:00  40.459999  11.392  51.841999  11.929 -11.536   
69679  2018-06-26 19:45:00  43.223999  12.146  54.737000  12.679 -11.536   

        LULL         OT  
0      1.311  38.661999  
1      1.258  38.223000  
2      1.258  37.344002  
3      1.215  37.124001  
4      1.215  37.124001  
...      ...        ...  
69675 -1.418  45.986500  
69676 -1.418  45.986500  
69677 -1.418  45.546501  
69678 -1.418  45.546501  
69679 -1.418  45.327000  

[69680 rows x 8 columns]

In [30]:
df_data = df_raw[['OT']]

In [31]:
train_data = df_data[0:9000]

In [32]:
from sklearn.preprocessing import StandardScaler

In [33]:
scaler = StandardScaler()

In [34]:
scaler.fit(train_data)

StandardScaler()

In [53]:
data = scaler.transform(df_data.values)

/Users/ray/.pyenv/versions/3.9.7/lib/python3.9/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [52]:
df_data

OT
0      38.661999
1      38.223000
2      37.344002
3      37.124001
4      37.124001
...          ...
69675  45.986500
69676  45.986500
69677  45.546501
69678  45.546501
69679  45.327000

[69680 rows x 1 columns]

In [36]:
df_stamp = df_raw[['date']][0:9000]

In [37]:
df_stamp

date
0     2016-07-01 00:00:00
1     2016-07-01 00:15:00
2     2016-07-01 00:30:00
3     2016-07-01 00:45:00
4     2016-07-01 01:00:00
...                   ...
8995  2016-10-02 16:45:00
8996  2016-10-02 17:00:00
8997  2016-10-02 17:15:00
8998  2016-10-02 17:30:00
8999  2016-10-02 17:45:00

[9000 rows x 1 columns]

In [38]:
df_stamp['date'] = pd.to_datetime(df_stamp.date)

In [41]:
df_stamp

date  month  day  weekday  hour  minute
0    2016-07-01 00:00:00      7    1        4     0       0
1    2016-07-01 00:15:00      7    1        4     0       1
2    2016-07-01 00:30:00      7    1        4     0       2
3    2016-07-01 00:45:00      7    1        4     0       3
4    2016-07-01 01:00:00      7    1        4     1       0
...                  ...    ...  ...      ...   ...     ...
8995 2016-10-02 16:45:00     10    2        6    16       3
8996 2016-10-02 17:00:00     10    2        6    17       0
8997 2016-10-02 17:15:00     10    2        6    17       1
8998 2016-10-02 17:30:00     10    2        6    17       2
8999 2016-10-02 17:45:00     10    2        6    17       3

[9000 rows x 6 columns]

In [44]:
df_stamp['month'] = df_stamp.date.apply(lambda row: row.month, 1)
df_stamp['day'] = df_stamp.date.apply(lambda row: row.day, 1)
df_stamp['weekday'] = df_stamp.date.apply(lambda row: row.weekday(), 1)
df_stamp['hour'] = df_stamp.date.apply(lambda row: row.hour, 1)
df_stamp['minute'] = df_stamp.date.apply(lambda row: row.minute, 1)
df_stamp['minute'] = df_stamp.minute.map(lambda x: x // 15)

/var/folders/3c/4336tt352pn6hnc003pk93080000gn/T/ipykernel_6593/3995856512.py:1: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  df_stamp['month'] = df_stamp.date.apply(lambda row: row.month, 1)
/var/folders/3c/4336tt352pn6hnc003pk93080000gn/T/ipykernel_6593/3995856512.py:2: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  df_stamp['day'] = df_stamp.date.apply(lambda row: row.day, 1)
/var/folders/3c/4336tt352pn6hnc003pk93080000gn/T/ipykernel_6593/3995856512.py:3: FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
  df_stamp['weekday'] = df_stamp.date.apply(lambda row: row.weekday(), 1)
/var/folders/3c/4

In [56]:
inverse = scaler.inverse_transform(data)

In [57]:
inverse

array([[38.66199875],
       [38.22299957],
       [37.34400177],
       ...,
       [45.54650116],
       [45.54650116],
       [45.32699966]])

In [28]:
num_vali = len(df_raw) - num_train - num_test

In [58]:
import numpy as np

In [71]:
perd_path = 'results/ETTm2_96_96_Autoformer_ETTm2_ftS_sl96_ll96_pl96_dm512_nh8_el2_dl1_df2048_fc3_ebtimeF_dtTrue_Exp_0/pred.npy'
ground_truth_path = "results/ETTm2_96_96_Autoformer_ETTm2_ftS_sl96_ll96_pl96_dm512_nh8_el2_dl1_df2048_fc3_ebtimeF_dtTrue_Exp_0/true.npy"
metric_path = "results/ETTm2_96_96_Autoformer_ETTm2_ftS_sl96_ll96_pl96_dm512_nh8_el2_dl1_df2048_fc3_ebtimeF_dtTrue_Exp_0/metrics.npy"
# Load the array from the .npy file
pred_result = np.load(perd_path)
ground_truth = np.load(ground_truth_path)
metric = np.load(metric_path)


In [65]:
ground_truth.shape

(395, 96, 1)

In [74]:
ground_truth_unscale = scaler.inverse_transform(ground_truth[0])

In [75]:
ground_truth_unscale

array([[25.576 ],
       [26.016 ],
       [26.016 ],
       [26.016 ],
       [26.016 ],
       [26.016 ],
       [26.2355],
       [26.2355],
       [26.2355],
       [26.2355],
       [26.2355],
       [26.2355],
       [26.455 ],
       [26.455 ],
       [26.455 ],
       [26.455 ],
       [26.455 ],
       [26.455 ],
       [26.455 ],
       [26.455 ],
       [26.455 ],
       [26.455 ],
       [26.455 ],
       [26.455 ],
       [26.455 ],
       [26.455 ],
       [26.455 ],
       [26.2355],
       [26.016 ],
       [26.016 ],
       [26.016 ],
       [25.796 ],
       [25.796 ],
       [25.796 ],
       [25.796 ],
       [26.016 ],
       [26.2355],
       [26.675 ],
       [27.1145],
       [27.5535],
       [28.213 ],
       [28.872 ],
       [29.531 ],
       [30.41  ],
       [31.0695],
       [31.729 ],
       [31.9485],
       [32.6075],
       [33.0465],
       [33.2665],
       [32.6075],
       [31.509 ],
       [31.289 ],
       [31.0695],
       [31.289 ],
       [31

In [66]:
pred_result.shape

(395, 96, 1)

In [72]:
pred_result_unscale = scaler.inverse_transform(pred_result[0])

In [73]:
pred_result_unscale

array([[24.423325],
       [24.483988],
       [24.431   ],
       [24.370872],
       [23.949236],
       [24.22384 ],
       [23.753664],
       [23.492048],
       [23.708649],
       [23.016954],
       [22.512615],
       [22.109327],
       [21.798685],
       [21.591875],
       [21.347216],
       [20.937702],
       [20.623074],
       [20.46063 ],
       [20.564587],
       [20.934866],
       [20.973095],
       [21.259502],
       [21.686666],
       [21.912949],
       [21.971313],
       [22.432436],
       [23.070595],
       [23.272861],
       [23.415367],
       [23.602741],
       [23.873062],
       [24.069155],
       [24.170311],
       [24.20167 ],
       [24.470673],
       [24.751492],
       [24.643929],
       [24.582397],
       [24.768478],
       [24.75818 ],
       [24.442888],
       [24.17532 ],
       [23.949562],
       [23.68163 ],
       [23.161083],
       [22.878437],
       [22.31772 ],
       [22.123098],
       [21.772003],
       [21.812773],


In [67]:
test_data_start = 12 * 30 * 24 * 4 + 4 * 30 * 24 * 4 - 720
test_data_start_end = 12 * 30 * 24 * 4 + 8 * 30 * 24 * 4

In [68]:
data_y = data[test_data_start:test_data_start_end]